grafana:
  adminPassword: admin123

  ingress:
    enabled: true
    ingressClassName: traefik

    hosts:
      - grafana.local

prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik

    hosts:
      - prometheus.local